apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: football
  template:
    metadata:
      labels:
        component: football
    spec:
      containers:
        - name: football
          image: oriolbellet/football
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq-cluster-ip-service
