apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: football
  template:
    metadata:
      labels:
        component: football
    spec:
      containers:
        - name: football
          image: oriolbellet/football:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              value: rabbitmq
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/gamedb
            - name: SPRING_DATASOURCE_USERNAME
              value: gamedb
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: validate
---
apiVersion: v1
kind: Service
metadata:
  name: football-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: football
