spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    driverClassName: org.postgresql.Driver
    username: gamedb
    password: postgres
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: validate

