### Play match
POST localhost:8080/football/api/v1/matches/0
Content-Type: application/json

### Create match
POST localhost:8080/football/api/v1/matches/
Content-Type: application/json

{
  "homeTeamId":"01fdbce4-7d10-4916-b71f-13cf61bbffe8",
  "awayTeamId":"1eb88008-6666-11eb-ae93-0242ac130002"
}

### Get teams
GET localhost:8080/football/api/v1/teams
Accept: application/json

### Get team
GET localhost:8080/football/api/v1/teams/01fdbce4-7d10-4916-b71f-13cf61bbffe8
Accept: application/json

### Get match
GET localhost:8080/football/api/v1/matches/0
Accept: application/json

###
GET localhost:8080/football/api/v1/season/standings
Accept: application/json

### Create game
POST localhost:8080/football/api/v1/games
Accept: application/json
Content-Type: application/json

{
  "userTeamId":"1eb88008-6666-11eb-ae93-0242ac130002"
}

### Get game teams
GET localhost:8080/football/api/v1/games/e3a3e100-45ad-4c3b-848f-ab348670a80c/teams
Accept: application/json

### Get standings
GET localhost:8080/football/api/v1/games/6f5b0499-fc1e-496f-9881-453336088c72/standings
Accept: application/json

### Play game gameweek
POST localhost:8080/football/api/v1/games/1b21b66c-ee75-4274-a003-89ab80bc6013
Accept: application/json

### Get game lineUp
GET localhost:8080/football/api/v1/games/1b21b66c-ee75-4274-a003-89ab80bc6013/lineup
Accept: application/json

### Change tactic
PUT localhost:8080/football/api/v1/games/6f5b0499-fc1e-496f-9881-453336088c72/tactic/T343

Accept: application/json

### Substitution<
PUT localhost:8080/football/api/v1/games/1b21b66c-ee75-4274-a003-89ab80bc6013/substitution
Accept: application/json
Content-Type: application/json

{
  "player1":"877f0912-82b3-4056-9e33-302b23473aca",
  "player2":"ae1e8bda-bd9c-4623-82a4-dab84e7b4d28"
}