POST localhost:8080/football/api/v1/matches/2
Content-Type: application/json

###
POST localhost:8080/football/api/v1/matches/
Content-Type: application/json

{
  "homeTeamId":"2",
  "awayTeamId":"3"
}

###
GET localhost:8080/football/api/v1/teams
Accept: application/json

###
